### ISSUE TITLE
IG quarks job is not mounting the links.

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/quarks-operator#1022]
**Describe the bug**
I´m running a quarks operator from `master` branch. I´m deploying a KUBECF that only have a diego-cell instance-group. This diego-cell consumes a link from `cloud_controller` as follows:
```yaml
  - type: replace
    path: /instance_groups/name=diego-cell/jobs/name=loggr-udp-forwarder/consumes?
    value:
      cloud_controller: {from: cloud_controller}
```
And I also define my links as follows:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: minion-link-cloud-controller
  labels:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
  annotations:
    quarks.cloudfoundry.org/provides: '{"name":"cloud_controller","type":"cloud_controller"}'
stringData:
  link: |
    system_domain: "{{ .Values.system_domain }}"
    app_domains: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    quarks.cloudfoundry.org/deployment-name: "{{ include "kubecf.deployment-name" . }}"
  annotations:
    quarks.cloudfoundry.org/link-provider-name: cloud_controller
  name: minion-service-cloud-controller
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minion-service-cloud-controller
subsets:
- addresses:
  - ip: 172.30.57.254
```

**To Reproduce**
Not sure, this can be more tricky because I did this for a multi-cluster PoC. I can help to reproduce this via pairing or similar.

**Expected behavior**
I would have expected to see my links mounted on the `ig` quarks-job as follows:
```yaml
          volumes:
          - name: minion-link-cloud-controller
            secret:
              secretName: minion-link-cloud-controller
          - name: minion-link-doppler
            secret:
              secretName: minion-link-doppler
          - name: desired-manifest-v1
            secret:
              secretName: desired-manifest-v1
          - emptyDir: {}
            name: instance-group
```
but the above was not the case. This lead to my `ig` to fail, as follows:

```sh
07/01 18:01:25 instance-group command failed. failed to resolve manifest.: Generate Job Consumes data failed for instance group diego-cell: cannot resolve non-optional link for provider cloud_controller in job loggr-udp-forwarder │
```

**Environment**
 - CF-Operator Version => https://ci.flintstone.cf.cloud.ibm.com/teams/quarks/pipelines/cf-operator/jobs/publish/builds/259
 - Kubecf is v2.2.2

**Additional context**
It worked before when using a patched cf-operator with https://github.com/cloudfoundry-incubator/quarks-operator/compare/vladi/entanglement-fixes.

**Comment by viovanov** [comment]
@manno it looks ok to me (what @qu1queee is trying to do) - any ideas?

**Comment by manno** [comment]
@viovanov yes, we looked at that.
https://github.com/cloudfoundry-incubator/quarks-operator/blob/master/pkg/kube/controllers/boshdeployment/link_infos.go#L37 is returning with `"manifest is not missing any link providers"`.

However https://github.com/cloudfoundry-incubator/quarks-operator/blob/master/pkg/bosh/manifest/cmd_instance_group_resolver.go#L468 fails.

We looked at the withops secret and the `provides:` was removed.

**Comment by qu1queee** [comment]
More insights on this:

1. Deploy quarks via `helm install cf-operator -n cf-operator https://s3.amazonaws.com/cf-operators/helm-charts/cf-operator-5.0.1%2B36.g29b51ee6.tgz  --set "global.singleNamespace.name=kubecf" --set "global.singleNamespace.create=true" --set "logLevel=trace"`

2. Apply some customize links in the `kubecf` namespace, e.g.:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: minion-link-nats
  labels:
    quarks.cloudfoundry.org/deployment-name: "kubecf"
  annotations:
    quarks.cloudfoundry.org/provides: '{"name":"nats","type":"nats"}'
stringData:
  link: |
    ---
    nats.user: "nats"
    nats.password: "UTO3yCeGxiR2Opey7b4WLt72bQSZkyYmdGtKMQzD477sNaS8BI7Wgy8jUZExUyPz"
    nats.hostname: "nats"
    nats.port: 4222
---
apiVersion: v1
kind: Service
metadata:
  labels:
    quarks.cloudfoundry.org/deployment-name: "kubecf"
  annotations:
    quarks.cloudfoundry.org/link-provider-name: cloud_controller
  name: minion-service-cloud-controller
spec:
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: minion-service-cloud-controller
subsets:
- addresses:
  - ip: 172.30.57.254
```

3. Deploy kubecf, by using the following `helm install kubecf -n kubecf https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.2.2/kubecf-v2.2.2.tgz -f values-coligo-kubecf-minions.yml`.  For `values-coligo-kubecf-minions.yml` you can use the following ops-files:
```yaml
# REQUIRED: the domain that the deployment will be visible to the user.
system_domain: foobar.com
operations:
  custom: []
  inline:
  # To deploy a cell
  - type: remove
    path: /instance_groups/name=adapter
  - type: remove
    path: /instance_groups/name=api
  - type: remove
    path: /instance_groups/name=auctioneer
  - type: remove
    path: /instance_groups/name=cc-worker
  - type: remove
    path: /instance_groups/name=diego-api
  - type: remove
    path: /instance_groups/name=doppler
  - type: remove
    path: /instance_groups/name=log-api
  - type: remove
    path: /instance_groups/name=log-cache
  - type: remove
    path: /instance_groups/name=nats
  - type: remove
    path: /instance_groups/name=router
  - type: remove
    path: /instance_groups/name=scheduler
  - type: remove
    path: /instance_groups/name=singleton-blobstore
  - type: remove
    path: /instance_groups/name=uaa
  - type: remove
    path: /instance_groups/name=rotate-cc-database-key
  - type: remove
    path: /instance_groups/name=smoke-tests?
  - type: remove
    path: /instance_groups/name=acceptance-tests?
  - type: remove
    path: /instance_groups/name=sync-integration-tests?
  - type: replace
    path: /instance_groups/name=diego-cell/jobs/name=loggr-udp-forwarder/consumes?
    value:
      cloud_controller: {from: cloud_controller}
  - type: replace
    path: /addons/name=prom_scraper/jobs/name=prom_scraper/consumes?
    value:
      loggregator: {from: loggregator}
  - type: replace
    path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/consumes?
    value:
      doppler: {from: doppler}
features:
  credhub:
    enabled: false
  routing_api:
    enabled: false
  embedded_database:
    enabled: true
```
