### ISSUE TITLE
DNS instances don't get updated when a new bosh-dns-alias is added

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#1111]
**Describe the bug**

After adding a new bosh-dns-alias using the following ops-file, the quarks-operator didn't update the generated CNAMEs:
```yaml
- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/-
  value:
    domain: service-discovery-controller.service.cf.internal
    targets:
    - deployment: kubecf
      domain: bosh
      instance_group: diego-cell
      network: default
      query: '*'
```

**To Reproduce**

Use the ops-file above after an initial kubecf installation and check that the DNS entries don't get updated.

**Expected behavior**

I should be able to resolve the newly added name.

**Environment**
 - quarks-operator version 5.2.0+0.g22cafc90.
