### ISSUE TITLE
Resource limits cause bogus resource requests.

### ISSUE THREAD

**Issue by andreas-kupries** [cloudfoundry-incubator/quarks-operator#1114]
**Describe the bug**

Setting a memory limit on a job not only generates a kube-level memory limit (:heavy_check_mark:), it __also generates__ an identical-sized memory request (:boom:). In other words, when I ask to to tell kube to keep the job's memory less than X the operator also forces the memory to be at least X. That is bogus.

**To Reproduce**

Deployed kubecf `0.2.0-1739.gfa5c9166-dirty` on minikube 1.8.2.
This used `cf-operator-6.0.2+0.g4eb7fc9f`

The deployment was modified using the ops patch
```
    - type: replace
      path: /instance_groups/name=nats/jobs/name=nats-tls/properties?/quarks/bpm/processes/name=nats-tls/limits/memory
      value: 40Mi
```
which limits the nats:nat-tls job to 40Mi.

In the rendered helm chart (secret `ops-with`) I find

```
- azs: null
  env: (...)
  instances: 1
  jobs:
  (...)
  - name: nats-tls
    properties:
      (...)
      quarks:
        bpm:
	  (...)
          processes:
          - hooks: {}
            limits:
              memory: 40Mi
            name: nats-tls
            unsafe: {}
        (...)
  (... other jobs)
  name: nats
  (...)
```

That looks ok, just a memory limit, no request in sight.

However, when looking at the nats pod itself I find
```
apiVersion: v1
kind: Pod
metadata:
  name: nats-0
  namespace: kubecf
spec:
  affinity:
  containers:
  (...)
  - (...)
    name: nats-tls-nats-tls
    resources:
      limits:
        memory: 40Mi
      requests:
        memory: 40Mi
    (...)
  (...)
```

My limit is present, good. The memory request however, not good, was not asked for.

**Expected behavior**

I expect to not see a memory request when I asked just for a limit.

**Environment**

  - cf-operator 6.0.2+0.g4eb7fc9f
  - kubecf 0.2.0-1739.gfa5c9166-dirty
