### ISSUE TITLE
Incorrect coredns config for alias with *

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry-incubator/quarks-operator#1118]
**Describe the bug**

The NATS has below dns alias:

```
      - domain: nats.service.cf.internal
        targets:
        - query: '*'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
```

When I tried to resolve a not-existed nats, KubeCF returned incorrect results.

The KubeCF has below 
```
/:/var/vcap/jobs/route_emitter# nslookup not-existed-nats.nats.service.cf.internal
Server:		172.21.147.233
Address:	172.21.147.233#53

not-existed-nats.nats.service.cf.internal	canonical name = nats.kubecf.svc.cluster.local.
Name:	nats.kubecf.svc.cluster.local
Address: 172.17.53.206
```

but in bosh VM, the results are :

```
nats/befdc14c-a3f1-452c-84b0-ec1b26f0f349:~# nslookup not-existed-nats.nats.service.cf.internal
Server:		169.254.0.2
Address:	169.254.0.2#53

** server can't find not-existed-nats.nats.service.cf.internal: NXDOMAIN
```

**To Reproduce**

Run `nslookup not-existed-nats.nats.service.cf.internal` in any KubeCF Pod

**Expected behavior**

KubeCF bosh-dns should behave the same with bosh-dns in bosh environment.

**Environment**
 - CF-Operator Version: 4.5.6

**Additional context**
Below are the generated coredns config:

```
template IN A nats.service.cf.internal {
	match ^(([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\.)*nats\.service\.cf\.internal\.$
	answer "{{ .Name }} 60 IN CNAME nats.kubecf.svc.cluster.local"
	upstream
}
```

maybe it should be:

```
template IN A nats.service.cf.internal {
	match ^nats\.service\.cf\.internal\.$
	answer "{{ .Name }} 60 IN CNAME nats.kubecf.svc.cluster.local"
	upstream
}
```
