### ISSUE TITLE
Image pull from a private repo for quarks-job, quarks-secret and coredns does not work as expected

### ISSUE THREAD

**Issue by divyaaswath** [cloudfoundry-incubator/quarks-operator#1233]
**Describe the bug**
Image pull from a private repo for quarks-job, quarks-secret and coredns does not work as expected.

Tried to get the cf-operator working with images from the private registry and have added the credentials for the registry to the global/image/credentials section which allows the cf-operator image to be pulled successfully however the other 3 images
coredns
quarks-job
quarks-secret
do not pick up the global credentials and hence the image pull for these components fails
```
global:
  image:
    credentials:
      username: xxxxxx
      password: xxxxxxxxxxxxxx
      servername: xxxxxxxxxxxx
image:
  repository: cf-operator
  org: private/repo
  tag: v6.1.17-0.gec409fd7
operator:
  boshDNSDockerImage: "private/repo/coredns:0.1.0-1.6.7-bp152.1.19"
quarks-job:
  image:
    org: private/repo
    repository: quarks-job
    tag: v1.0.206
quarks-secret:
  image:
    org: private/repo
    repository: quarks-secret
    tag: v1.0.744
```

**To Reproduce**
Provide private repository details to get the quarks-job, quarks-secret and coredns images in the values yaml file.

**Expected behavior**
Images should be pulled successfully.

**Environment**
 - CF-Operator Version - 6.1.17+0.gec409fd7
 - Kubecf - 2.6.1

**Additional context**
Installation is done on OpenShift version 4.4
