### ISSUE TITLE
Overriding optional bosh link consumers in the deployment manifest doesn't seem to work

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/quarks-operator#1259]
The docs at https://bosh.io/docs/links/#explicit state:

> Optional consumers may be specified as nil in the deployment manifest to block consumption of any providers.

In kubecf we have done this to disable link resolution for `postgres` for the `credhub` instance group. Looking at `desired-manifest-v1` shows:

```
      jobs:
      - consumes:
          postgres: null
        name: credhub
```

However, `ig-resolved.credhub-v1` still references the autoscaler database:

```
          quarks:
            consumes:
              postgres:
                address: asdatabase
```

We've ultimately worked around this with an `ig_resolver` patch, modifying the `job.MF` of the `credhub` job, but I think the explicit link resolution should have worked as well.
