### ISSUE TITLE
Often getting multiple jobs after updating kubecf ops-files

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#750]
When I apply a change, I usually get multiple `bpm` and `ig` jobs:

```
NAME                                READY   STATUS       RESTARTS   AGE
bpm-kubecf-31a221bf58edc585-26ps4   0/20    Init:24/30   0          65s
bpm-kubecf-bcd5e3c7eeb0a857-647cg   0/20    Init:21/30   0          52s
ig-kubecf-b7e2c93ab14bbdb3-kmrqp    0/20    Init:19/30   0          52s
ig-kubecf-e142d0c421e1f13d-cbddz    0/20    Init:23/30   0          65s
```

In this case, I simply changed the `cloud_controller_ng` properties:

```
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: internal
    rules:
    - destination: {{ required "A valid 'kube.service_cluster_ip_range' is required!" .Values.kube.service_cluster_ip_range | quote }}
      protocol: all
    - destination: {{ required "A valid 'kube.pod_cluster_ip_range' is required!" .Values.kube.pod_cluster_ip_range | quote }}
      protocol: all
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: internal
```
