### ISSUE TITLE
Provide (or document) a mechanism to specify a deployment variable value

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/quarks-operator#895]
I want to be able to specify a variable value when deploying kubecf, e.g.

```
bosh deploy ... -v cf-admin-password=cant-guess-this
```

I assumed that there is a mechanism already, as the main point of using variables is to make it easier for users to configure settings without having to write ops-files. Indeed often ops-files are provided upstream, that add additional variables to make their operations configurable by the user.

I'm aware that variables also provide a mechanism to generate default values for password/keys/certs at deployment time, but those are meant as defaults when the user doesn't explicitly specify a value.

I haven't thought about the best way to implement this, but assume it would be something like a `var-file` section that can be added to a deployment request.

**Comment by viovanov** [comment]
@jandubois you can already provide a non-generated value by creating the variable's secret yourself.

https://github.com/cloudfoundry-incubator/cf-operator/blob/master/README.md#variables

https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/from_bosh_to_kube.md#manual-implicit-variables

**Comment by viovanov** [comment]
please reopen if there's something still missing

**Comment by jandubois** [comment]
I think there are several issues with the current mechanism:

## All variables have to be pre-defined in the helm chart

Assume you want to explicitly specify `((pxc_tls.ca))`. There is currently no way to do this via overriding something in `values.yaml`; you have to add a file to the chart template directory to do so, which feels very wrong to do for an end user.

The only way to avoid this would be to explicitly templatize the deployment manifest where the variable is used. And we would have to do this for *all* variables, introduced by *any* ops file. This is a lot of extra effort, and still does not allow for custom ops-files to add variables on the fly.

It would be so much simpler to have a mechanism in `values.yaml` to set

```
variables:
  pxc_tls.ca: "..."
```

This requires no custom work in the kubecf chart and makes *all* variables overridable by default. It is just a one-time modification to pass this block somehow to the operator.

The logic in the operator should be rather simple: any time an explicit value is provided, it overwrites the generated one. Or maybe it doesn't change the generation at all, and this block is just passed on to the template expanders, which will prefer the user values and only query the generated secrets when the user didn't provide a value.

## Replacing a generated value with a user provided one

Assuming the user has already deployed kubecf with default (generated) values, but wants to upgrade to provide the CA value explicitly. Helm cannot create the secret now because it already exists, and is not owned by this release. So it needs some active mechanism to delete the secret first, but only if it exists. This does not fit the helm deployment model.

## Exposing the variable implementation to the end user

The internal field name for variables depends on the type of the variable. Implicit variables are stored in `data.value`, passwords in `data.password` etc. So unless the kubecf chart maintains a list of all variables and their type, the user will have to specify in which field to store them. This is exposing an operator implementation detail to the end user.

# Example

When I look at the implementation of support for an external blobstore (cloudfoundry-incubator/kubecf#608), I see a ton of changes made to kubecf. I would expect to be able to configure this as an end-user without requiring explicit support from kubecf at all (beyond bundling the upstream ops files):

Conceptually (and simplified) all that should be needed in `values.yaml` is:

```
operations:
  use-external-blobstore.yml
  use-s3-blobstore.yml

variables:
  blobstore_access_key_id: ...
  blobstore_secret_access_key: ...
  aws_region: ...
```

The variables are already the templating mechanism for ops-files; there should be no need to wrap yet another helm templating mechanism around it. Adding it to helm adds a big maintenance burden to keep it up-to-date, and doesn't allow the flexibility to provide custom ops files with new variables after the chart has already been released.

**Comment by jandubois** [comment]
The support for external databases in cloudfoundry-incubator/kubecf#162 is another example that should be much simpler by using the https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-external-dbs.yml ops file plus a block of variable settings.

I'm kind of dismayed to see us introduce a one-to-one mapping between our own "structured" variable names to bosh "flat" variable names; that layer just adds maintenance and documentation burden, and I can see very little advantage in doing this, neither for us nor for the end user.

**Comment by jandubois** [comment]
Another usage example that came up in discussion today: When importing a database dump from SCF into kubecf, where SCF has never done an encryption key rotation, we currently need something like this in `values.yaml`:

```
properties:
  api:
    cloud_controller_ng:
      cc:
        db_encryption_key: "secret_value"
  cc-worker:
    cloud_controller_worker:
      cc:
        db_encryption_key: "secret_value"
  scheduler:
    cc_deployment_updater:
      cc:
        db_encryption_key: "secret_value"
    cloud_controller_clock:
      cc:
        db_encryption_key: "secret_value"
```

@f0rmiga optimized this to:

```
properties:
  api:
    cloud_controller_ng: &cc_encryption
      cc:
        db_encryption_key: "secret_value"
  cc-worker:
    cloud_controller_worker: *cc_encryption
  scheduler:
    cc_deployment_updater: *cc_encryption
    cloud_controller_clock: *cc_encryption
```

But if we could set variable values from `values.yaml`, then all you would need would be:

```
variables:
  cc_db_encryption_key: "secret_value"
```

because `db_encryption_key` is implemented in the cf-deployment manifest in all 4 places as:

```
...
  properties:
    cc:
      db_encryption_key: "((cc_db_encryption_key))"
```
